### ISSUE TITLE
Many Name Erros in unsloth-zoo 

### ISSUE THREAD

**Issue by developer0hye** [unslothai/unsloth-zoo#27]
![image](https://github.com/user-attachments/assets/34485286-4988-4910-a980-cf32d7f16278)

![image](https://github.com/user-attachments/assets/5c834179-160f-4b5a-838c-1cf24cc24d56)

![image](https://github.com/user-attachments/assets/e8ee061e-e992-43a5-b22f-01410181069a)

**Comment by danielhanchen** [comment]
Apologies - I fixed most bugs on saving - I guess I should have left it on the nightly branch and not pushed it into main - I tested Llama 3.2 and Qwen 2 VL saving, and it should work now!

Sorry on the issue again! Please update unsloth_zoo via `pip install --upgrade --no-cache-dir --no-deps unsloth_zoo`

**Comment by developer0hye** [comment]
@danielhanchen Thanks!
